# escape=`

# Stage 0: prepare files
FROM microsoft/aspnet:4.7.2-windowsservercore-1803 AS prepare

ARG CONFIG_PACKAGE

SHELL ["powershell", "-NoProfile", "-Command", "$ErrorActionPreference = 'Stop';"]

ADD files/$CONFIG_PACKAGE /Files/

RUN Expand-Archive -Path /Files/$Env:CONFIG_PACKAGE -DestinationPath /Files/Config


# Stage 1: create actual image
FROM microsoft/aspnet:4.7.2-windowsservercore-1803

ARG SQL_SA_PASSWORD
ARG SQL_DB_PREFIX
ARG SQL_SERVER="mssql"
ARG SITE_NAME="xconnect"
ARG SOLR_CORE_PREFIX="xp0"
ARG SOLR_PORT="8983"
ARG XCONNECT_PACKAGE

SHELL ["powershell", "-NoProfile", "-Command", "$ErrorActionPreference = 'Stop';"]

# Install chocolatey
RUN Set-ExecutionPolicy Bypass -Scope Process -Force; iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))

# Install WebDeploy
RUN choco install -y --params="Quiet" --limit-output --no-progress webdeploy

# Install IIS URL Rewrite
RUN choco install -y --params="Quiet" --limit-output --no-progress UrlRewrite

# Install VS Remote Tools for debugging
RUN choco install -y --params="Quiet" --limit-output --no-progress visualstudio2017-remotetools

COPY files/license.xml /Files/
COPY files/$XCONNECT_PACKAGE /Files/
COPY files/*.pfx /Files/
COPY --from=prepare /Files/Config /Files/Config/
ADD scripts /Scripts

ENV SOLR_CERT_PATH "c:\\Files\\solr.pfx"
ENV XCONNECT_CERT_PATH "C:\\Files\\xConnect.client.pfx"
ENV XCONNECT_SSL_PATH "C:\\Files\\xconnect.pfx"

# Trust Self signed certificates
RUN /Scripts/Import-Certificate.ps1 -certificateFile $Env:SOLR_CERT_PATH -secret 'secret' -storeName 'Root' -storeLocation 'LocalMachine'
RUN /Scripts/Import-Certificate.ps1 -certificateFile $Env:XCONNECT_CERT_PATH -secret 'secret' -storeName 'Root' -storeLocation 'LocalMachine'
RUN /Scripts/Import-Certificate.ps1 -certificateFile $Env:XCONNECT_SSL_PATH -secret 'secret' -storeName 'Root' -storeLocation 'LocalMachine'

# Import XConnect certificate
RUN /Scripts/Import-Certificate.ps1 -certificateFile $Env:XCONNECT_CERT_PATH -secret 'secret' -storeName 'My' -storeLocation 'LocalMachine'
RUN /Scripts/Import-Certificate.ps1 -certificateFile $Env:XCONNECT_SSL_PATH -secret 'secret' -storeName 'My' -storeLocation 'LocalMachine'

RUN /Scripts/Install-SIF.ps1

RUN Remove-Website -Name 'Default Web Site'

ENV SIF_CONFIG="c:\\Files\\Config\\xconnect-xp0.json"

RUN $config = Get-Content $Env:SIF_CONFIG | Where-Object { $_ -notmatch '^\s*\/\/'} | Out-String | ConvertFrom-Json; `
    $config.Tasks.InstallWDP.Params.Arguments | Add-Member -Name 'Skip' -Value @(@{'ObjectName' = 'dbDacFx'}, @{'ObjectName' = 'dbFullSql'}) -MemberType NoteProperty; `
    ConvertTo-Json $config -Depth 50 | Set-Content -Path $Env:SIF_CONFIG

RUN $solrUrl = 'https://solr:{0}/solr' -f $Env:SOLR_PORT; `
    Install-SitecoreConfiguration -Path $Env:SIF_CONFIG `
    -Package c:/Files/$Env:XCONNECT_PACKAGE `
    -LicenseFile "c:\\Files\\license.xml" `
    -Sitename $Env:SITE_NAME `
    -XConnectCert "xConnect.client" `
    -SSLCert "xConnect" `
    -SqlDbPrefix $Env:SQL_DB_PREFIX `
    -SqlServer $Env:SQL_SERVER `
    -SqlAdminUser "sa" `
    -SqlAdminPassword $Env:SQL_SA_PASSWORD `
    -SqlCollectionUser "sa" `
    -SqlCollectionPassword $Env:SQL_SA_PASSWORD `
    -SqlProcessingPoolsUser "sa" `
    -SqlProcessingPoolsPassword $Env:SQL_SA_PASSWORD `
    -SqlReferenceDataUser "sa" `
    -SqlReferenceDataPassword $Env:SQL_SA_PASSWORD `
	-SqlMessagingUser "sa" `
    -SqlMessagingPassword $Env:SQL_SA_PASSWORD `
    -SqlMarketingAutomationUser "sa" `
    -SqlMarketingAutomationPassword $Env:SQL_SA_PASSWORD `
    -SolrCorePrefix $Env:SOLR_CORE_PREFIX `
    -SolrURL $solrUrl `
    -Skip "CleanShards", "CreateShards", "CreateShardApplicationDatabaseServerLoginSqlCmd", "CreateShardManagerApplicationDatabaseUserSqlCmd", "CreateShard0ApplicationDatabaseUserSqlCmd", "CreateShard1ApplicationDatabaseUserSqlCmd", "ConfigureSolrSchemas"

RUN Remove-Item -Recurse -Force -Path c:\inetpub\wwwroot\xconnect\App_Data\logs

# Add Host entries for Docker services
RUN /Scripts/Add-Hosts.ps1

RUN Start-WebAppPool -Name $Env:SITE_NAME
RUN Start-Website -Name $Env:SITE_NAME

EXPOSE 443

ENTRYPOINT ["powershell", "-NoProfile", "-Command", "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'Continue'; $verbosePreference='Continue';", "C:\\Scripts\\Start-RemoteDebug.ps1;", "C:\\ServiceMonitor.exe", "w3svc"]